[package]
name = "torchrs"
version = "0.1.0"
authors = ["Matt Macy <mmacy@torch.rs>"]

[dependencies]
rutorch = { path = "rutorch" }
modparse_derive = { path = "modparse_derive"}
num = "^0.1.37"
rand = "^0.3"
linked-hash-map = "0.4.2"